export const skyxProduction = {
  accountId: "129346407469",
  region: "us-east-1",
  vpc: {
    id: "vpc-0118132a0a68f1f8b",
    cidr: "10.42.0.0/16",
    publicSubnetIds: [
      "subnet-042eb9e7a021e2d63",
      "subnet-02158e7027fc2fe61",
    ],
    privateSubnetIds: [
      "subnet-0d1bd575ca1de7c76",
      "subnet-05bac08a52afb3bbb",
    ],
    internetGatewayId: "igw-006aff6fae065b876",
    publicRouteTableId: "rtb-04e64702680756bd4",
    mainRouteTableId: "rtb-054e90743d9ff91ab",
    natGatewayCount: 0,
    skyxVpcEndpointCount: 0,
    externalEndpoints: [
      {
        id: "vpce-0be79b16f26533b68",
        type: "Gateway",
        service: "com.amazonaws.us-east-1.s3",
        vpcId: "vpc-08afe822bbaef16c8",
        vpcName: "aws-controltower-VPC",
        policy: "Allow principal * action * resource *",
        ownership: "external Control Tower resource; do not import into SkyX",
      },
    ],
    securityGroupIds: {
      alb: "sg-0fb59dedab7b7aa9c",
      task: "sg-0d08082390032bcfe",
      database: "sg-08dfa784deaaf3a4e",
    },
  },
  ecs: {
    clusterName: "skyx-prod",
    api: {
      serviceName: "skyx-api",
      serviceArn:
        "arn:aws:ecs:us-east-1:129346407469:service/skyx-prod/skyx-api",
      taskDefinition: "skyx-api:5",
      containerPort: 8000,
      imageRepository: "skyx-backend",
      logGroup: "/ecs/skyx-api",
      deploymentCircuitBreaker: { enable: true, rollback: true },
      deploymentCloudWatchAlarms: false,
    },
    frontend: {
      serviceName: "skyx-frontend",
      serviceArn:
        "arn:aws:ecs:us-east-1:129346407469:service/skyx-prod/skyx-frontend",
      taskDefinition: "skyx-frontend:1",
      containerPort: 3001,
      imageRepository: "skyx-frontend",
      logGroup: "/ecs/skyx-frontend",
      deploymentCircuitBreaker: { enable: true, rollback: true },
      deploymentCloudWatchAlarms: false,
    },
    taskExecutionRoleName: "SkyXEcsTaskExecutionRole",
    desiredCount: 1,
    autoscaling: {
      api: { minCapacity: 1, maxCapacity: 4, targetCpuUtilization: 60 },
      frontend: { minCapacity: 1, maxCapacity: 3, targetCpuUtilization: 60 },
    },
    serviceConnect: false,
    serviceDiscovery: false,
    availabilityZoneRebalancing: true,
    autoAssignPublicIp: true,
  },
  loadBalancers: {
    api: {
      name: "skyx-prod-alb",
      arn: "arn:aws:elasticloadbalancing:us-east-1:129346407469:loadbalancer/app/skyx-prod-alb/daa606ab7cfc22fc",
      targetGroupName: "skyx-prod-api",
      targetGroupArn:
        "arn:aws:elasticloadbalancing:us-east-1:129346407469:targetgroup/skyx-prod-api/b07e0985d7d24599",
      listenerArn:
        "arn:aws:elasticloadbalancing:us-east-1:129346407469:listener/app/skyx-prod-alb/daa606ab7cfc22fc/04b7e22e969f7840",
      ruleArn:
        "arn:aws:elasticloadbalancing:us-east-1:129346407469:listener-rule/app/skyx-prod-alb/daa606ab7cfc22fc/04b7e22e969f7840/29412e36ad4e142b",
      listener: "HTTP:80",
      ruleCount: 1,
      ruleConditions: "default rule; no conditions",
      targetGroupStickiness: false,
      healthCheck: {
        protocol: "HTTP",
        path: "/health/live",
        port: "traffic-port",
        healthyThreshold: 5,
        unhealthyThreshold: 2,
        timeoutSeconds: 5,
        intervalSeconds: 30,
        successCodes: "200",
      },
      responseHeaders: "none",
      serverHeader: true,
      attributes: {
        tlsVersionHeaders: false,
        wafFailOpen: false,
        http2: true,
        connectionIdleTimeoutSeconds: 60,
        clientKeepaliveSeconds: 3600,
        desyncMitigationMode: "defensive",
        dropInvalidHeaderFields: false,
        xForwardedFor: "append",
        clientPortPreservation: false,
        preserveHostHeader: false,
        crossZoneLoadBalancing: true,
        arcZonalShift: "disabled",
        deletionProtection: false,
        accessLogs: false,
        connectionLogs: false,
        healthCheckLogs: false,
      },
    },
    frontend: {
      name: "skyx-prod-frontend-alb",
      arn: "arn:aws:elasticloadbalancing:us-east-1:129346407469:loadbalancer/app/skyx-prod-frontend-alb/7841fca276b64cd7",
      targetGroupName: "skyx-prod-frontend",
      targetGroupArn:
        "arn:aws:elasticloadbalancing:us-east-1:129346407469:targetgroup/skyx-prod-frontend/dba8ae93ab308987",
      listenerArn:
        "arn:aws:elasticloadbalancing:us-east-1:129346407469:listener/app/skyx-prod-frontend-alb/7841fca276b64cd7/05ef8d1e540d6061",
      ruleArn:
        "arn:aws:elasticloadbalancing:us-east-1:129346407469:listener-rule/app/skyx-prod-frontend-alb/7841fca276b64cd7/05ef8d1e540d6061/ffdc84d92b445da8",
      listener: "HTTP:80",
      ruleCount: 1,
      ruleConditions: "default rule; no conditions",
      targetGroupStickiness: false,
      healthCheck: {
        protocol: "HTTP",
        path: "/sign-in",
        port: "traffic-port",
        healthyThreshold: 5,
        unhealthyThreshold: 2,
        timeoutSeconds: 5,
        intervalSeconds: 30,
        successCodes: "200",
      },
      responseHeaders: "none",
      serverHeader: true,
      attributes: {
        tlsVersionHeaders: false,
        wafFailOpen: false,
        http2: true,
        connectionIdleTimeoutSeconds: 60,
        clientKeepaliveSeconds: 3600,
        desyncMitigationMode: "defensive",
        dropInvalidHeaderFields: false,
        xForwardedFor: "append",
        clientPortPreservation: false,
        preserveHostHeader: false,
        crossZoneLoadBalancing: true,
        arcZonalShift: "disabled",
        deletionProtection: false,
        accessLogs: false,
        connectionLogs: false,
        healthCheckLogs: false,
      },
    },
  },
  database: {
    clusterIdentifier: "skyx-prod-db",
    clusterArn: "arn:aws:rds:us-east-1:129346407469:cluster:skyx-prod-db",
    engine: "aurora-postgresql",
    engineVersion: "17.7",
    port: 5432,
    deletionProtection: true,
    backupRetentionDays: 30,
    pointInTimeRecovery: true,
    encryptionKeyAlias: "alias/aws/rds",
  },
  identity: {
    userPoolId: "us-east-1_wiOmAOPbu",
    userPoolArn:
      "arn:aws:cognito-idp:us-east-1:129346407469:userpool/us-east-1_wiOmAOPbu",
    appClientId: "6vouk7sil2f8ohbo7maah044n2",
  },
  repositories: {
    backend: "skyx-backend",
    frontend: "skyx-frontend",
  },
  secrets: [
    "skyx/prod/frontend-auth-cookie-secret",
    "skyx/prod/cursor-secret",
    "skyx/prod/scope-token-secret",
    "skyx/prod/local-jwt-secret",
    "skyx/prod/database-ingest-url",
    "skyx/prod/database-app-url",
    "skyx/prod/database-admin-url",
  ],
  iam: {
    apiTaskRole: {
      name: "SkyXApiTaskRole",
      trustPrincipal: "ecs-tasks.amazonaws.com",
      policies: ["SkyXApiTaskRolePolicy"],
      cognitoActions: ["cognito-idp:AdminCreateUser", "cognito-idp:AdminGetUser"],
      previousObservedCognitoResource:
        "arn:aws:cognito-idp:us-east-1:*:userpool/*",
      observedCognitoResource:
        "arn:aws:cognito-idp:us-east-1:129346407469:userpool/us-east-1_wiOmAOPbu",
      intendedCognitoResource:
        "arn:aws:cognito-idp:us-east-1:129346407469:userpool/us-east-1_wiOmAOPbu",
      permissionsBoundary: false,
    },
    ecsTaskExecutionRole: {
      name: "SkyXEcsTaskExecutionRole",
      trustPrincipal: "ecs-tasks.amazonaws.com",
      policies: [
        "AmazonECSTaskExecutionRolePolicy",
        "SkyXFrontendSecretRead",
        "SkyXSecretsRead",
      ],
      permissionsBoundary: false,
    },
    githubActionsEcrRole: {
      name: "SkyXGitHubActionsEcrRole",
      trustPrincipal: "token.actions.githubusercontent.com",
      oidcAudience: "sts.amazonaws.com",
      policies: [
        "SkyXEcrPush",
        "SkyxEcsMigrationRunTask",
        "SkyxEcsPassRole",
      ],
      permissionsBoundary: false,
    },
    codeBuildRole: {
      name: "SkyXCodeBuildRole",
      trustPrincipal: "codebuild.amazonaws.com",
      policies: [
        "AmazonEC2ContainerRegistryPowerUser",
        "CloudWatchLogsFullAccess",
        "SkyXCodeBuildUseGitHubConnection",
      ],
      githubConnectionArn:
        "arn:aws:codeconnections:us-east-1:129346407469:connection/a81f64fb-13ee-411e-8cfa-4eed0a6672d7",
      permissionsBoundary: false,
    },
  },
  observability: {
    cloudWatchAlarmCount: 0,
    wafWebAclCount: 1,
    wafWebAcl: {
      name: "skyx-prod-regional-count",
      arn: "arn:aws:wafv2:us-east-1:129346407469:regional/webacl/skyx-prod-regional-count/5179ccf1-bc92-4347-814e-d9667a2201b2",
      mode: "COUNT",
      logging: false,
      associatedLoadBalancers: ["skyx-prod-alb", "skyx-prod-frontend-alb"],
    },
    acmCertificateCount: 0,
    config: {
      recorder: "on",
      frequency: "continuous",
      retention: "7 years",
      ownership: "Control Tower / AWS Config boundary requires review",
    },
  },
} as const;
